### ISSUE TITLE
1.18 Inventorio Fix Suggestion

### ISSUE THREAD

**Issue by DedicatedMedic** [spAnser/reacharound#11]
Hello, sorry if this is bothersome but I think the 1.18 version could be made compatible with Inventorio with relative ease?
https://github.com/spAnser/reacharound/issues/7

I copied the ClientMixIn and  renamed the RefMap over the 1.18 version and things appear to be working, at least for myself.

Copying more than or using the 1.19 version by editing the Fabric.json fails due to the Vec3i change in PlacementFeature (or any other reason that I didn't chance to notice, I'm not very bright) causing crashes when a block could be placed via ReachAround.

**Comment by spAnser** [comment]
Added that PR to the 1.18 branch. Should have versions up shortly on Modrinth/Curse
