### ISSUE TITLE
Fix Pix,As you can see

### ISSUE THREAD

**Issue by surfishs** [spAnser/reacharound#13]
![image](https://github.com/spAnser/reacharound/assets/96485650/cc0e4863-4890-43ce-936b-e9171f697787)
The horizontal line and the center are not aligned

**Comment by spAnser** [comment]
What version of Minecraft are you using?
Are you using any other mods?
Are you using any texture packs?

**Comment by surfishs** [comment]
> 

I will try to test your module alone in a pure environment, please wait.
I'm using Minecraft 1.20, currently the latest farbic loader.

**Comment by surfishs** [comment]
![image](https://github.com/spAnser/reacharound/assets/96485650/aa9406d4-da1e-44f0-beaa-8a8504a5514b)
I deleted all other mods, leaving only this mod, the problem still exists.
But it looks like the problem has lessened a bit?
![Uploading image.png…]()
But I think this is still different from the effect in your demo video, I think the two lines should be exactly horizontal to the collimation.

**Comment by surfishs** [comment]
![image](https://github.com/spAnser/reacharound/assets/96485650/ed5883fa-f421-4e21-aec4-a40ed9883d6e)
But I think this is still different from the effect in your demo video, I think the two lines should be exactly horizontal to the collimation.

**Comment by spAnser** [comment]
I manually test the mod every update. It still looks like my video. I have even changed the gui scale just to see if that was the issue but it didn't change anything.

In a pure environment I assume you also didn't change any game settings.

Are you potentially using a desktop scale other than 100%?

![image](https://github.com/spAnser/reacharound/assets/193938/1fdc3df1-15c3-4bd5-908c-3c7ff9fde324)

There are alternative looks to choose from are they all offset? I imagine they will be though.
