### ISSUE TITLE
feat: More configuration options

### ISSUE THREAD

**Issue by exincore** [spAnser/reacharound#2]
This mod looks great and the UI is also quite nice, but it is not yet as customizable as I think it should be. I, and I'm sure others, would like at least these options:

* Switch for horizontal/vertical/both reach-around types 
* Color field (with alpha) for the overlay
* Animation type (none, linear, quadratic... fade) and duration

I might try a swing at implementing these, but Java is not my forté.

**Comment by spAnser** [comment]
I'm open to pull requests but might also take a look at doing these at some point.

Also by switch for types. Are you thinking a config option or a keybind that swaps between the modes.

**Comment by exincore** [comment]
> Also by switch for types. Are you thinking a config option or a keybind that swaps between the modes.

All of these I'm thinking of config options. It seems to detect which mode to use pretty well

**Comment by exincore** [comment]
I'm working on ~~"Switch for horizontal/vertical/both reach-around types" in my fork~~ all of it
