### ISSUE TITLE
Question about 1.21.1

### ISSUE THREAD

**Issue by vico93** [spAnser/reacharound#23]
By chance, does this mod works on 1.21.1?

I'm using [Bridging Mod](https://modrinth.com/mod/bridging-mod) currently but folks told me the reacharound this mod uses is more like how Quark offered back then.

If this works with 1.21.1 (and maybe 1.21.2) i would switch over.

**Comment by spAnser** [comment]
It does work with 1.21.1 but 1.21.2 and 1.21.3 will need an update it seems.
