### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by IZeeXeS** [spAnser/reacharound#4]
Highlight block you are looking at

**Comment by spAnser** [comment]
Are we thinking render a ghost block? Or just highlighting the block it would attach to?

**Comment by IZeeXeS** [comment]
> Are we thinking render a ghost block? Or just highlighting the block it would attach to?

Render a selection box in place where block appear

**Comment by spAnser** [comment]
I finally got around to doing some research into how to accomplish this and I have an early preview finally.


https://github.com/spAnser/reacharound/assets/193938/a69bbd51-bf12-49e3-b6c2-50969a2d6ee7

**Comment by spAnser** [comment]
Forgot to mention this in commit message but I think it is ready. I will be porting this to all other versions sometime this weekend and prep a new release.

https://github.com/spAnser/reacharound/commit/a5bd601ab4e9f026700d90e10785e424648f113e

The options will be updated to toggle 2D / 3D on or off individually.

These are the new 3D Options
Style can be toggled between `Both | Outline | Solid`

![image](https://github.com/spAnser/reacharound/assets/193938/54242e1d-452f-4f0d-8c66-fdcfd636c508)

Here is the 3D with a creeper obstructing the placement with the default settings.

![image](https://github.com/spAnser/reacharound/assets/193938/1511381a-29bc-4abf-83f4-6bee71e735aa)

**Comment by spAnser** [comment]
1.3.0 Release is out on Curseforge/GitHub Releases/Modrinth
