### ISSUE TITLE
1.1.1 crashes with Bedrockify

### ISSUE THREAD

**Issue by SplendidAlakey** [spAnser/reacharound#9]
**MC** 1.19.2
**QFAPI** 4.0.0-beta.25
**Reacharound** 1.1.1
**[Bedrockify](https://www.curseforge.com/minecraft/mc-mods/bedrockify)** 1.5.1

Reverting to Reacharound 1.1.0 lets the game work.

Bedrockify does have a sort of reacharound block placing, BE style, but prior to the latest Reacharound update both mods worked together just fine.

~~The issue doesn't happen on Fabric.~~ It does, I tested incorrectly.

As a workaround you can disable reacharound mixin in Bedrockify's config.

Logs: https://gist.github.com/SplendidAlakey/a8b8e7f9a2426bccb9c57d2da6dc8e43

**Comment by spAnser** [comment]
1.1.1 added support for inventorio by moving the mixin used. it likely is now conflicting with bedrockify.

Not sure what the best fix would be. Maybe finding a new mixin location could work.

**Comment by SplendidAlakey** [comment]
I reported this in case it was a bug, rather than an intended change. Since this is intentional and provides better compat with other mods, I'd say it would be better to just disable Bedrockify's mixin.

Unless you can find a better way to do this without regressing the compatibility aspect brought by the previous patch, I'd say close this issue and I could ask the dev of Bedrockify to do that automatically, if Reacharound is detected, they did a similar patch for another mod before.

I only wish to keep both functionalities, due to Bedrockify mimicking [BE reacharound placement](https://i.imgur.com/SVMlIH0.gif), which can be done with Reacharound, but with a bit less fluidity, since the goal of Reacharound is different.

**Comment by spAnser** [comment]
Yeah might be something I can take a look at at some point.

**Comment by SplendidAlakey** [comment]
Bedrockify released an update, refactoring their reacharound mixin to be more compatible with mods, so both mods now work together again. I also confirmed, that the fix works on Quilt, as well as Fabric.
